[package]
name = "lang"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.3"
derive_more = "0.99.16"
isa = { path = "../isa" }
